### ISSUE TITLE
Ship Humanizer 2.0

### ISSUE THREAD

**Issue by onovotny** [Humanizr/Humanizer#501]
This is a tracking issue for shipping Humanizer 2.0

- [x]  MyGet team to release update for better handling of satellite packages
- [x] #506 Update gh-pages docs to reflect the latest
- [x] #507 Remove obsolete members
- [x] #502 Documentation of package split into `Humanizer`, `Humanizer.Core` and `Humanizer.Core.<locale>`
- [x] #492 Default language resources missing for a few resources 
- [x] #470 Build warning VS2015
- [x] #465 Drop support for .NET 4 and Silverlight 5
- [x] #451 Support `dotnet` TFM 
- [x] #238 Change DefaultDateTimeHumanizeStrategy to turn 60 min to one hour not 45 
- [x] #234 Remove Plurality enum 
- [x] #101 Add precision to DateTime.Humanize 
- [x] #59 Getting only needed resources on nuget install 

The biggest thing left right now is a sane way to publishing the 39 packages from MyGet to NuGet.org. The MyGet team has a fix coming for this in the next couple of weeks.

There is also an outstanding issue running the UWP unit tests, but this appears to be related to the multi-threaded execution of the tests. There may also be race conditions in UWP's ResourceManager class. Neither one of those should affect the majority of apps that set/use a single culture on startup.

The current packages are always available on the CI feed:

Ver | Url 
---   |  --- 
NuGet v2 | https://www.myget.org/F/humanizer/api/v2 
NuGet v3 | https://www.myget.org/F/humanizer/api/v3/index.json

**Comment by onovotny** [comment]
/cc @hazzik @mexx @MehdiK

Anything missing from the above list?

**Comment by onovotny** [comment]
Beta 2 was just published to NuGet.org: https://www.nuget.org/packages/Humanizer/2.0.0-beta02-0092

**Comment by hazzik** [comment]
We also need to do this one: https://github.com/Humanizr/Humanizer/issues/234

**Comment by onovotny** [comment]
@hazzik, should be done as part of #507. I don't see any more obsolete methods in the code.

Question is now back in #506. Technically we're ready to ship, just need a decision on the docs for the main website or see who has time to do it.

**Comment by onovotny** [comment]
:shipit:

**Comment by onovotny** [comment]
building the final tagged release and will push it to nuget in the next few hrs :) :tada:

**Comment by onovotny** [comment]
It's live. I'm writing up an announcement blog post and will tweet that shortly.

**Comment by onovotny** [comment]
Announcement is live

https://oren.codes/2016/01/30/announcing-humanizer-2-0/
http://www.twitter.com/onovotny/status/693533580819980290

**Comment by hazzik** [comment]
Nice
